### ISSUE TITLE
Improve status reporting

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#109]
Status reporting for a group must list all runs with return codes.
Current implementation shows:
```cheetah.py status -g sim -d

kmehta/sim : DONE, 1 / 6 failed
  == total runs: 6
  state         done: 6
  state       killed: 0
  state  not_started: 0
  state      running: 0

  == total w/ reason: 6
  reason      failed: 1
  reason   succeeded: 5

  == total return codes: 6
  return code 0: 5
  return code 134: 1
```

This shows one run failed, but does not show which run.
Group status could list run results here, instead of having to do `status -c`

**Comment by bd4** [comment]
The two options have different purposes: -d is a summary that is short even for large jobs, and lets you see at a glance if there are any problems that need further investigation. -c gives the complete list of return codes, which can be very long and requires grepping to figure out if anything went wrong. You can specify both options if you want both for small groups. I'm up for improving or renaming -d, but I want to keep it short.

**Comment by kshitij-v-mehta** [comment]
maybe `-s` for summary, and `-d` that lists all runs and whether they succeeded/failed

**Comment by bd4** [comment]
Ya I guess there is a missing level, currently there is a summary with counts and per-component codes organized by runs, but there is no list of all runs with top level run status only (and no component return codes)

**Comment by bd4** [comment]
Another gap: once you find a failing run you want to examine, there is a shortcut for showing stdout/err (`-o`), which is very useful, but it's also important to know which parameters were used for that run. Adding a `-p` option for displaying each run's params would be useful. It is available in the run dir as codar.cheetah.run-params.json, could be printed as lines of `name: value`.

**Comment by bd4** [comment]
-p was added to dev branch in 8aff2377b5ae498bbc60c475277132d6cf3c18c0. That leaves renaming -d to -s and making -d display top level run status

**Comment by bd4** [comment]
Final design:
```
$ ./cheetah.py status -h
usage: cheetah.py status [-h] [-u [USER [USER ...]]] [-g [GROUP [GROUP ...]]]
                         [-r [RUN [RUN ...]]] [-c [CODE [CODE ...]]] [-s] [-l]
                         [-v {CRITICAL,ERROR,WARNING,INFO,DEBUG}] [-n] [-t]
                         [-p] [-o]
                         campaign_directory

Get status of an existing campaign

positional arguments:
  campaign_directory    Top level campaign directory

optional arguments:
  -h, --help            show this help message and exit
  -u [USER [USER ...]], --user [USER [USER ...]]
                        Show status for specific user(s) only
  -g [GROUP [GROUP ...]], --group [GROUP [GROUP ...]]
                        Show status for specific sweep group(s) only
  -r [RUN [RUN ...]], --run [RUN [RUN ...]]
                        Show status for specific run(s) only
  -c [CODE [CODE ...]], --code [CODE [CODE ...]]
                        Show status for specific code(s) only
  -s, --group-summary   Show a summary of statistics for each group
  -l, --logs            Show workflow log file for each group
  -v {CRITICAL,ERROR,WARNING,INFO,DEBUG}, --log-level {CRITICAL,ERROR,WARNING,INFO,DEBUG}
                        Display messages of specified level or above (requires
                        --logs)
  -n, --run-summary     Show a summary for each run
  -t, --return-codes    Show return codes for components within each run
                        (implies -n)
  -p, --show-parameters
                        Show parameter values for each run (implies -t and -n)
  -o, --print-code-output
                        Show stderr and stdout for codes within each run
```

**Comment by bd4** [comment]
Fix in dev branch.
