### ISSUE TITLE
No. of DataSpaces server instances is different for DATASPACES and DIMES

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#112]
DataSpaces supports two transport types: DATASPACES and DIMES.
DIMES is RDMA based, and requires fewer server instances to be spawned as compared to DATASPACES, which buffers all data at the server.

Cheetah should add spawn the correct no. of server instances depending on the transport type selected by the user.

**Comment by kshitij-v-mehta** [comment]
Additionally, in the same workflow, some codes may connect using DATASPACES, whereas some may connect using DIMES. This must be taken into account to calculate the no. of server instances required.

**Comment by bd4** [comment]
Since we're using DATASPACES on theta and DIMES on titan, is this a blocker for cluster2018 paper? What is the formula for each?

**Comment by kshitij-v-mehta** [comment]
This is not a blocker for the paper. When using DATASPACES, we need more dataspaces server than when using DIMES, as DIMES uses RDMA as compared to DATASPACES, which buffers data at the server.

**Comment by kshitij-v-mehta** [comment]
Fixed in PR #129
