### ISSUE TITLE
Incorporate changes in sos_flow config

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#115]
Merge branch ecp_demo to include generation of file sos_flow.config file. Edit generation of the config file to incorporate recent changes in sos_flow.

**Comment by bd4** [comment]
Is this cluster_2018 blocker?

**Comment by kshitij-v-mehta** [comment]
Yes, but this is simple. Should take me a few minutes to get done.

**Comment by kshitij-v-mehta** [comment]
Not required for post-processing with sosflow. Thus, not required for the paper.
Only required if live, online analysis of sos data needs to be performed.
