### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#136]
Update outdated examples to build with the latest release.

**Comment by bd4** [comment]
Are there specific examples that don't build now, or are you referring to how they will become outdated as we change the spec etc for 1.0?

**Comment by kshitij-v-mehta** [comment]
We have multiple examples with heat-transfer, and I was thinking about merging them into one example for heat-transfer

**Comment by bd4** [comment]
The examples serve two purposes - documentation (some are linked from the README) and tests. I think maybe merging them into two examples, one simple and one with all features in use, may be reasonable. But that might make it more confusing for someone who just wants for example SOS, if they see all this other stuff enabled in the example.
