### ISSUE TITLE
Basic support for running on summit

### ISSUE THREAD

**Issue by bd4** [CODARcode/cheetah#137]
Need to support bsub scheduler and jsrun runner. See https://www.olcf.ornl.gov/for-users/system-user-guides/summit/ . ~~Supporting summitdev is not critical but it may be easy given that they run the same stacks (but at different versions which might cause problems). If nothing else, summitdev can be used to develop the support until we have access to summit.~~

This should be basic support for jsrun without advanced options to co-locate processes from different executables, binding processes etc.

**Comment by kshitij-v-mehta** [comment]
Fixed in release 1.0
