### ISSUE TITLE
Improve campaign process control

### ISSUE THREAD

**Issue by bd4** [CODARcode/cheetah#14]
A convenience script 'kill.sh' that kills all processes associated with the campaign would be extremely useful, although it may be tricky to support across all schedulers. In addition, the status and wait script no longer work after the transition to swift.

**Comment by abidmalik1967** [comment]
@bd4 I successfully ran the heat equation using the Cheetah framework. Have some questions:

-  I got a number 94.3099943 at the end of the run. What does it mean?

- I see three directories with the profile directories run-*. Are these three different configurations?

- How do you know that the run doesn't want? Is there any particular message for this?
