### ISSUE TITLE
Support for scheduler option to specify node files

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#150]
Schedulers provide an option to specify a 'node file'. For example, 'aprun -l nodefile ...' .
Extend Cheetah user interface to provide node-file support.

**Comment by kshitij-v-mehta** [comment]
Fixed in 
https://github.com/CODARcode/cheetah/commit/9126ee4dbe071e133ae40784708489f8d9602f6f

**Comment by suchyta1** [comment]
I think #153 might be the same, I'll try out `sched_args`
