### ISSUE TITLE
command line param to specify reduction on a variable

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#2]
Add param type for modifying adios.xml and setting data reduction on a variable(s)

**Comment by kshitij-v-mehta** [comment]
we could have a command line param like `cheetah .. --transform <var name>`
Cheetah will need to know the name of the xml file to edit it. 
Thus, we need to provide the xml file name as well.

Something like `cheetah ... ---transform <varname:trasform_name:transform_options> --xml <xml file>`

e.g. `cheetah .. --transform "dT:zfp:accuracy=0.1" --xml heat_transfer.xml`

**Comment by bd4** [comment]
none of the other params are specified on cheetah command line, they are specified in the campaign definition py file, within a sweep. Is there some reason to make this different?

**Comment by kshitij-v-mehta** [comment]
That is a better suggestion. I will make it part of the campaign definition py file.
