### ISSUE TITLE
Support for named arguments

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#20]
Support for named arguments for an application:
e.g. ./app -a 10 -b 20 etc.

Example argument specification in application spec file:
`p.ParamCmdLineArg("heat", "iterations", 7, "-i", [5,10,20])`

Feature originally requested by Tahsin Kurc for LAMMPS.

**Comment by bd4** [comment]
This is already supported:
https://github.com/CODARcode/cheetah/blob/master/codar/cheetah/parameters.py#L331

There is a brief note about it at the end of the readme in the campaign spec description, but documentation could certainly be improved (especially an example experiment file).
