### ISSUE TITLE
status reports IN PROGRESS after jobs have been canceled.

### ISSUE THREAD

**Issue by chuckatkins** [CODARcode/cheetah#205]
When running on `rhea` with slurm, if I kill the group jobs with the generated `cancel.sh` script, then `cheetah status -u <username> -g <groupname>` still reports `IN PROGRESS` even after the job has entirely left the queueing system.

**Comment by kshitij-v-mehta** [comment]
Fixed. After a job is cancelled using the cancel script, the status reporting correctly reports that the job has ended.

However, if a Cheetah job times out, it doesn't leave time for the main thread to update the status of the experiments, and it still reports it as 'in progress'. To fix this, Cheetah will have to ping the scheduler about the job id. This is being addressed in a separate issue.
