### ISSUE TITLE
Need for timeouts

### ISSUE THREAD

**Issue by ianfoster** [CODARcode/cheetah#21]
A potential failure case for Cheetah (which I seem to have encountered) is that an experiment is started and it never completes (at least not for modest values of "never").

I propose that for us to be able to do useful codesign runs, we need to be able to specify a maximum time for a run, after which the run should be terminated (and reported as terminated).

**Comment by bd4** [comment]
When using PBS and other schedulers, we can let the scheduler take care of the time limit. To simulate on local runs, we'd need to spawn a supervisor process or something. Maybe we can get away with just having a kill option for local runs?

**Comment by ianfoster** [comment]
I wondered whether Swift could handle that. It is surely something that it needs for other purposes.

**Comment by bd4** [comment]
When using a scheduler, swift does handle timeouts via the WALLTIME env var. Cheetah just has to set it. I think the campaign writer should decide on the limit, although I guess there could be a default value as well.

**Comment by jmjwozniak** [comment]
Yes, the WALLTIME variable is simply passed to the scheduler at job submission time.  It applies to the whole workflow.

**Comment by jmjwozniak** [comment]
Done: https://github.com/CODARcode/SwiftExamples/commit/288be115ee958a850b652700b44d4678fda23b4d
