### ISSUE TITLE
Develop workflow script to replace MPIX Launch

### ISSUE THREAD

**Issue by bd4** [CODARcode/cheetah#23]
Because of issues with MPIX Launch on Cray (#18), we need an alternative solution for launching applications. The basic idea is to have a Python script that runs on the login and/or service nodes and submits mpiexec/aprun jobs as resources free up, grouping them based on the needs of the application. Basic requirements for cheetah:

- work with applications that involve multiple codes (e.g. heat_transfer + stage_write)
- allow setting nprocs per code
- allow setting total nprocs to allow multiple concurrent runs (e.g. if app takes 12 total procs across all codes, could allow 36 concurrent procs for 3 concurrent application runs)
- support arguments containing spaces and other special characters
- allow setting number of nodes
- support setting timeouts per application run, not just per batch
- support detecting when application runs finish, and why (timeout, error exit, normal exit). This could be done through adhoc application wrapper scripts and output files, but it's worth considering baking into the workflow script in some way.

To make this more concrete, the workflow script could read a list of runs in JSON format:
```
[
{
  "nodes": 4,
  "programs": [
     { "exe": "/path/to/heat_transfer_adios2",
       "args": ["first arg", "2nd arg", "arg with\\ chars \" needing escape"],
       "nprocs": 12 },
    { "exe": "/path/to/stage_write",
      "args": [....],
      "nprocs": 2 }
   ]
},
{  ... },
{ ... }
]
```

Some open questions:
- how will this interact with swift?
- should this script run on login node and generate scheduler batches on the fly, or should a single batch be used to execute it (e.g. on cray service nodes), so a large multi batch run would involve multiple instances of the workflow script, and each instance just goes through a set of program runs?
- how much of cheetah functionality should be moved into this workflow script? This script could be useful for other applications besides cheetah, so ideally we maintain some separation, but there is an opportunity here to simplify some of the messy code generation in cheetah. The first version should be very simple, but this is something to consider for future.

**Comment by jmjwozniak** [comment]
Let's make Swift interaction a separate issue

**Comment by bd4** [comment]
Additional requirements:
- control working directory
- control redirection of stderr and stdout
These could be set by passing additional JSON keys.

One approach to tracking individual runs is to add another key, say 'return_code_file', to the JSON, that specifies a file to write out the application return code.

The workflow script could also support post-run and post-batch hooks to be executed on compute and/or login nodes. This is an example of moving cheetah functionality into the workflow script, and how it can give more flexibility (easier to run on compute nodes).

**Comment by bd4** [comment]
@jmjwozniak so is the idea that the core workflow script is pure Python, no dependencies on swift? Then swift/cheetah/whatever can make use of it as needed?

**Comment by jmjwozniak** [comment]
Yes, the service is a simple Python program.  Swift will be able to connect to it from inside the same qsub script.

**Comment by kshitij-v-mehta** [comment]
Could you elaborate a little on the above comment? I am not sure I understand what it means by swift being able to connect to it from the same qsub script. 

We are going to develop a python script that will read an app's json spec and submit jobs. This script would probably be part of cheetah, and would run on the login node. Each job would be submitted using swift, is that correct?

**Comment by bd4** [comment]
If the workflow script runs inside a qsub (or other scheduler batch), then I think it would submit jobs directly using mpiexec or aprun, and not use swift at all. Re swift connecting inside the same qsub, I think Justin means if the workflow script was reading from a pipe (could be local named pipe or maybe in future network), then swift could be the other side of that pipe generating the jobs to run.

I think ideally this workflow script is not part of Cheetah, but it's design is informed by the requirements of Cheetah and certain applications using swift (e.g. machine learning model parameter exploration from CANDLE).

**Comment by bd4** [comment]
I'm working on a prototype that runs inside a batch, i.e. on a compute node (or a service node under cray). It uses 3 threads: one consumes pipelines from a queue and starts them as process slots become available, one producing adds pipelines to the queue (initially by reading from a flat file, both could be network service in future), and one that monitors the spawned subprocesses and marks them as complete so the consumer can start new pipelines.

**Comment by mw70** [comment]
I'm sorry to be slow to get to this thread -- we implemented some of our research code this way, using a set of nested forked shells within the qsub environment.  Each of the bash script loops would look for a coordination message and then kill/restart/initialize one of their managed processes in the workflow.  We had one loop for each component in the workflow.  It's probably similar code to what you've put together, but if comparing to what we'd implemented for that would be useful, I can point you to it.

**Comment by kshitij-v-mehta** [comment]
@mw70 It would be great if you could provide a pointer to it, it would be nice if I could take a look.
@bd4 Could you push the current changes to a new branch, so that I can go over it?

**Comment by bd4** [comment]
@kshitij-v-mehta It's very much a work in progress (does not run) but I saved what I have so far, might give a clearer idea of the design: https://github.com/CODARcode/cheetah/tree/workflow-script

**Comment by bd4** [comment]
Basic workflow script with a test script is up in that branch now. It needs some refactoring, but the basic idea is there.
