### ISSUE TITLE
Setting different environments for coupled executables launched via EFFIS

### ISSUE THREAD

**Issue by stephethier** [CODARcode/cheetah#246]
Hi Folks,
I’ve been having a discussion with Eric Suchyta about launching a GENE-XGC coupled simulation via EFFIS. The non-EFFIS job script looks like this:
```
#!/bin/bash -l
#BSUB -nnodes 262
#BSUB -W 2:00
#BSUB -J ECP
#BSUB -q debug

cd GENE
source /some_path/gene_env
jsrun -n 6 -r 1 -a 32 -g 0 -c 32 --bind rs ../gene_exec_summit &> gene.${out} &

cd ../XGC
source /some_path/xgc_env
jsrun -n 1536  -r 6 -a 1 -g 1 -c 7 --bind rs ../xgc_exec_summit &> xgc.${out} &

wait
```
Now the files **gene_env** and **xgc_env** contain a bunch of “module load …” statements after doing a module purge. The environment for GENE is different from XGC since the former is built with gcc and the latter with nvhpc. Even the dependencies that they have in common have been built separately.
So the question I asked Eric was how to specify separate environments in EFFIS within a **run:** section. He said that it was only possible through the **env:** section by setting LD_LIBRARY_PATH and whatever else needs to be specified through environment variables. He said it had to do with the way Cheetah launches an executable by creating a subprocess.

Would it be possible to implement a better way to set up different environments for codes that require potentially conflicting shared libraries? This seems to be a Cheetah shortcoming.

Thanks!
Stephane

**Comment by kshitij-v-mehta** [comment]
This has been fixed and tested in EFFIS.
