### ISSUE TITLE
new feature: have cheetah figure out min/max number of nodes

### ISSUE THREAD

**Issue by bd4** [CODARcode/cheetah#26]
For a given sweep group and target machine, it should be possible to figure out the minimum number of nodes required and the maximum number of nodes (max => adding more would not increase throughput). If Cheetah calculates this, it can raise an error if the user specifies a nodes parameter outside the range.

**Comment by bd4** [comment]
It would also be useful if Cheetah understood machine scheduler policy, and would give an early error if the spec violates policy. For example, on titan: https://www.olcf.ornl.gov/kb_articles/titan-scheduling-policy/

**Comment by bd4** [comment]
Input: cheetah spec with user specified number of nodes to use for each user app. Output: number of nodes needed for extra pieces: dataspaces, sosflow

**Comment by kshitij-v-mehta** [comment]
Input should be no. of MPI tasks for each user app, plus the node layout. Output should be the minimum no. of nodes that should be allocated.

**Comment by bd4** [comment]
Minimum number of nodes for the entire SweepGroup / scheduler job, right? Each run may have a different minimum, so it will be the max of all the mins.

**Comment by kshitij-v-mehta** [comment]
Yes, that's correct.
