### ISSUE TITLE
new feature: specify different node counts in Sweeps

### ISSUE THREAD

**Issue by bd4** [CODARcode/cheetah#30]
While the total number of nodes for a scheduler job is fixed, those nodes could be utilized to run multiple experiments in parallel. It may be possible to do this with only minor tweaks to the spec, and I think it will already work with the workflow script which is just executing FOBs to fill available resources. The exaalt experiment is a good example - see if we can get it to run as a single job.

**Comment by ianfoster** [comment]
Or at least run different experiments with different numbers of nodes, all less than or equal to the number of nodes allocated.

**Comment by kshitij-v-mehta** [comment]
@bd4 This is fixed using node-layout. Close this issue?
