### ISSUE TITLE
Parameter dependencies

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#32]
Add a new feature that enables dependencies between application arguments. 
Example:
`aprun -n 12 heat_transfer 4 3 500 600 1 1`

The decomposition of heat_transfer (4*3) must be equal to the no. of procs used to run the application.

In a campaign spec file, since these are separate args, we cannot specify dependency between them.

```
p.ParamRunner("heat", "nprocs", [4,8,16]),
p.ParamCmdLineArg("heat", "xprocs", 2, [2]),
p.ParamCmdLineArg("heat", "yprocs", 3, [2]),
``` 

In essence, how do you specify a different no. of `xprocs` and `yprocs` for different `nprocs`?

**Comment by bd4** [comment]
Idea: allow specifying a function instead of a list of values. You could specify xprocs and yprocs explicitly, and then use a function for nprocs that takes a dict of all the other params (and in this case would get and multiply xprocs and yprocs).

**Comment by kshitij-v-mehta** [comment]
Something like the following?
```
p.ParamRunner("heat", "nprocs", product(xprocs,yprocs)),
p.ParamCmdLineArg("heat", "xprocs", 2, [2]),
p.ParamCmdLineArg("heat", "yprocs", 3, [2]),
```

How do you get a reference to the xprocs and yprocs values?
Also, we need a way to specify that we do not want a full dot product of all xprocs and yprocs, just a product of the xproc-value and yproc-value at each `i` for `i=0..len(xprocs)`. That is,
if `xprocs=[2,4]` and `yprocs=[2,2]`,
then `nprocs = [4,8]` and NOT `nprocs=[4,4,8,8]`.

**Comment by bd4** [comment]
I was thinking a generic python function that takes a dictionary:
```
p.ParamRunner("heat", "nprocs", lambda params: params["xprocs"] * params["yprocs"])
```
The spec file is just Python, so we are limited to python syntax, but also have the full power of python to allow for more complex specifications.

**Comment by bd4** [comment]
Re cross products, the behavior I was imagining is that if you specify a function for a certain parameter instead of a list, it is never part of the cross product. It's value is fully determined by the other values.
