### ISSUE TITLE
Add experiments to an existing campaign directory

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#33]
Users should be able to add new experiments to an existing campaign directory. 
Currently, cheetah creates sweep groups starting with `group-001`, because of which new experiments need to be created in a separate campaign directory, else existing sweep group directories would be overwritten.

**Comment by bd4** [comment]
Maybe the default behavior if the directory exists should be to fail with an error? Then add options `--force-overwrite` and `--force-add` which replace or add to an existing experiment.

**Comment by bd4** [comment]
This is a bit messy - does cheetah need to parse the existing experiment to determine if any of the already present groups have changed? Is this an update to the original campaign file that adds new SweepGroups, or a second campaign file? Copying the campaign file to the campaign dir is something cheetah should be doing anyway, but there are still lots details to work out on how exactly it should behave.

**Comment by kshitij-v-mehta** [comment]
What if we look at the `group-xxx` directories existing in the campaign location pointed to by the user on the cheetah run command, and begin the new group names starting with `group-x+1`?

I did not think about whether users would add to the existing spec file or create a new one ..

**Comment by bd4** [comment]
I'm concerned if they edit the spec, they will expect it to update existing groups as well, and then there must be logic to determine which of the groups are new and which are old (wouldn't want to re-add the ones that are already there). If it's a separate spec file, then would need to keep a mapping of spec file SweepGroups to group numbers.

What is the exact use case for this? Did it come up for exaalt runs? It's one of those features that sounds simple at first, but is actually really confusing and hard to design well.

**Comment by kshitij-v-mehta** [comment]
When working with exaalt, I had to create many new experiments depending on the results of the previous run, and had to write them to new campaign directories. It would have been good to have all the experiments in one campaign directory. 

One way is to manually create a top-level campaign dir and then manually create sub-campaign-dirs whenever new experiments need to be created. Seems like bit of a hassle though.

>  If it's a separate spec file, then would need to keep a mapping of spec file SweepGroups to group numbers

Why do we need to do that? When there is a new, separate spec file, we just browse through the existing campaign dir and note the highest group-xxx dir and create new ones starting with group-x+1.

**Comment by mw70** [comment]
So it would seem that the idea of keeping a manifest of experimental items that have been completed might be handy.  Could be something as simple as a hashmap -- you create the entry when a particular experiment instance/FOB is set, and then you set the value to 1 when that particular combination is done.  That way you could conceivably add something to a campaign over time, and the python launcher could just check whether that particular combo has already run.  You might need to be careful about how you generate the hash -- for example, if you want to have the same thing run 3 times to get good statistics, you have to have the count number in the hash, or else you'll only ever run one.

Of course, this starts getting close to the scheduler logic that already exists inside swift.

**Comment by bd4** [comment]
I think it's important for the campaign dir to be self describing, it should be easy to figure out which spec file and which sweepgroup corresponds to which group dir.

Manually creating new experiments is a hassle - but so is hashing sweep groups and having complex logic for determining add vs update and avoiding contaminating existing runs. I'm totally open to adding some sort of feature here, but I want a more detailed plan first.

**Comment by bd4** [comment]
assume cheetah has an add or update operation. Questions:
- what happens if the same spec file is used but just with new sweep groups? does cheetah detect this and only add new ones? what if old are changed and have already been run? How are the multiple versions tracked in campaign file?
- if using new spec file, how is this tracked in campaign dir?

Maybe what we should do is introduce some notion of a related series of campaigns. I'd like to make campaigns immutable other than complete overwrite (with results removed), but allow follow up campaigns to be run in an organized way.

**Comment by kshitij-v-mehta** [comment]
> what happens if the same spec file is used but just with new sweep groups? does cheetah detect this and only add new ones?

No, we only allow new spec files. Everything in a new spec file is treated as a new set of experiments.

> if using new spec file, how is this tracked in campaign dir?

There are two options that we can consider.
Option [1]:
When a new spec file is given, we first check if the campaign-directory pointed at by the user is empty. If not, then get the highest group-xxx name and start from group-x+1. Now the spec file can be deleted, we don't need it. 

Now when you cd into the campaign directory and run `run-all.sh`, it will check which groups have been run (using a manifest file), and only run the groups that are not yet run.

Option [2]:
Cheetah creates a sub-campaign dir in the campaign directory.
So, when the user does `cheetah.py -o exaalt_campaign`, cheetah creates something like 
`exaalt_campaign/1/group-001` etc. 
The next time a user submits more experiments to the same campaign directory using `cheetah.py -o exaalt_campaign (<-- note the same campaign dir)`, cheetah creates `exaalt_campaign/2/` and creates all new sweep groups there.

**Comment by kshitij-v-mehta** [comment]
Cheetah will ultimately need to maintain a campaign-level results file as well. 
A user may want to run hundreds of experiments, and cheetah will need to analyze the results using a post-processing script. But we cannot wait for the full campaign to complete, as each experiment may create data that may have to be removed before other experiments are run. This will be especially true for experiments that generate significant amounts of data.

So, cheetah will have to parse results as experiments complete, add them to a campaign-level results file, and then users/cheetah may delete the data generated by the experiment. This is a separate issue, but we need to keep it in mind as we prepare for our next paper. 
I feel we need to get our heads together and design the architecture of Cheetah carefully and take all minute details into account.

**Comment by kshitij-v-mehta** [comment]
To answer your earlier question, once a sweep group is created, it is immutable. No new experiments can be added to the group. Only new groups can be created.

**Comment by bd4** [comment]
I like option 2, it allows us to have a standard sub-campaign dir hierarchy, e.g. copy the spec file to the sub-campaign dir. Each sub-campaign could be submitted separately, and detailed results tracked in it's subdir, but a top level campaign progress file could still be maintained tracking status of each sub-campaign (new, running, failed, complete, etc). Keeping a log of when each sub-campaign is added, run, re-run, etc also seems useful.

**Comment by bd4** [comment]
#79 is related to this

**Comment by bd4** [comment]
A use case related to this: performance profiling often requires doing lots of different runs with different parameters, experimenting as you go. Keeping track of all the runs and the parameters (app level and node layout/system level) is tedious, and it seems like a great basic use case for cheetah. This is not so much a well planned co design study as meander through the parameter space. The spec file is less important, having self contained run directories with easy to extract results is important. Post analysis that collects all the results is also useful. Filtering of the results will likely be needed, since only certain runs will end up being worth looking closely at, but that is easy enough to do in an adhoc fashion. Small Sweeps cat be useful, but it will be just as common to submit a group with only a single run with fully specified parameters.

Assigning friendly names to each run is also helpful. Cheetah only supports naming at the group level, which is probably good enough, but maybe another feature where custom run dir name patterns are allowed is worth considering.

**Comment by bd4** [comment]
Another desirable feature for feature for performance profiling use case: the output directory would ideally be self contained and easy to pass off to other team members not familiar with savanna/cheetah software, so they could run it themselves and understand how the application was configured for the run (environment, scheduler options, application options, etc should be very easy to find).

**Comment by kshitij-v-mehta** [comment]
Fixed in PR #45
