### ISSUE TITLE
Insert delay between component invocations

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#36]
Users may occasionally desire to insert a `sleep(x)` between invocations of components in a pipeline. Cheetah should either always do this as a default step, or provide a way to the user to specify a sleep interval.

**Comment by bd4** [comment]
Can you specify some examples? Does order matter? This will also be a workflow feature, and cheetah will just pass the value on. Runs in a FOB could include an invocation number for ordering and a delay.

**Comment by kshitij-v-mehta** [comment]
We could have the following workflow:
```
aprun tau_daemon
sleep(5)

aprun stage_write
sleep(5)

aprun exaalt
sleep(5)
```

**Comment by bd4** [comment]
Proposed design:

For cheetah, make codes and ordered dict with sub-dicts for configuration:
```
codes =[ ('tau', dict(exe='tau/tau_daemon`, sleep_after=5)),
               ('stage', dict(exe='stage_write/stage_write', sleep_after=5)),
               ('exaalt', dict(exe='exaalt', sleep_after=5)),]
```

For workflow, can just add `sleep_after` key, the format already uses a list for a pipeline spec, so can just make sure to execute in that order.

**Comment by kshitij-v-mehta** [comment]
+1
