### ISSUE TITLE
Get running on Theta

### ISSUE THREAD

**Issue by ianfoster** [CODARcode/cheetah#39]
(Please delete if this is not the right place for this issue.)

We need to get Cheetah+Savanna+(Heat, EXAALT) running on Theta.

**Comment by bd4** [comment]
For cheetah, we just need to support Cobalt scheduler, which looks fairly similar to PBS. That will be the easy part - getting adios + stage_write + heat + exaalt built on theta will be the hard part.

**Comment by bd4** [comment]
Working with Pi example, still requires testing with other examples.

**Comment by kshitij-v-mehta** [comment]
Fixed in PR #62
