### ISSUE TITLE
Enable Tau support

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#42]
Enabling support for TAU requires the following: 

1. Create a sub-dir for each component in every run directory. e.g.
```
group-001/run-001/tau-exaalt
group-001/run-001/tau-stage
```

2. Store the tau_dir for each component in preferably, run-params.json.

3. Set the environment variable PROFILEDIR to point to the component's Tau dir during Popen.

4. Create a tau.conf file in each run dir that will contain finer level tau configuration options. We can statically set the options for now.

The tau-directory for the component must be stored somewhere so that a post-processing script can retrieve the path to the profile dir.

**Comment by bd4** [comment]
Does there need to be a per-code (exaalt vs stage etc) tau.conf, or is it always per run?

**Comment by kshitij-v-mehta** [comment]
The tau.conf will be per run
