### ISSUE TITLE
sosflow for a subset of Run components

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#57]
Cheetah is currently setup to use sosflow with all components of a Run. However, we need the ability to run it with a subset of run components.
E.g. in a workflow consisting of dataspaces + two xgc apps + 4 visualization apps, only the xgc apps will be linked with tau, and thus, sosflow must be setup to work only with them.

**Comment by bd4** [comment]
Is this just a matter of not setting the env vars for those components and not incrementing the node offsets for them? We could make sosflow a list of component names instead of a bool.

**Comment by kshitij-v-mehta** [comment]
thats correct, the components without sosflow must be ignored during calculation of node offsets for components with sosflow.

I was thinking we let the bool stay, that would be a good way to disable/enable sosflow for the group altogether. 

For per-rc sosflow, I am adding an option to the codes var in the campaign. 
`codes = [('stage', dict(exe="stage_write/stage_write", sleep_after=5, sosflow=True))]`

**Comment by bd4** [comment]
Ok cool I like that spec change.
