### ISSUE TITLE
Ability to specify modules and env vars for campaign

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#60]
Some applications may need to export environment variables such as `OMP_NUM_THREADS=1` prior to running an experiment. We need to add a way for a user to specify additional environment variables that can be set by Cheetah when a run is made. 

Suggestion: For every sweep, provide a `ENV_VARS=<list> or <filename>` option where env vars are specified in the spec file in a list, or in a file that can be read by Cheetah. Not sure which is better: specifying them in the spec file itself or having them read in from a file on disk.

**Comment by bd4** [comment]
I think an external bash file that can be sourced, like a per-app machine config, is better. It allows for doing module load and sourcing other bash files, in addition to setting env vars. The machine configs should be updated to only contain things necessary to run workflow (typically module load python). We can also add some example app configs.

**Comment by bd4** [comment]
For now I'm going to assume that all codes will be using the same environment.
