### ISSUE TITLE
Adios xml param does not take component subdirs into account

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#66]
The `ParamAdiosXML` parameter that is used to set values in the adios xml file looks for the xml file in the run directory. If `component_subdirs` is set to True, the xml file exists in the component subdirectory, and not in the run directory. Cheetah looks for the xml file in the run directory, does not find it, and crashes.

**Comment by bd4** [comment]
I wonder if both component_subdirs and component_inputs should be moved to the top level campaign spec, out of the SweepGroup. Confusing that inputs is specified at top level and component_inputs is per group, and I don't think we have a use case for different component subdirs/inputs in each group.
