### ISSUE TITLE
Display error and exit if number of nodes not adequate

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#67]
Cheetah does not check if the no. of nodes is adequate to run the pipeline. If a user specifies fewer nodes, Cheetah does not catch the issue, and the workflow engine hangs after submitting a subset of the components.

**Comment by bd4** [comment]
I think both cheetah and workflow should check for this. Workflow so it doesn't hang if passed an unrunnable fob, and cheetah for early detection/convenience.
