### ISSUE TITLE
Successful runs are being marked as timedout

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#77]
Seeing reports like the following in `codar.workflow.status.json` for successful runs, where `reason` is reported as `timeout` even though the run has successfully completed in the allotted time.
```
  "run-000": {
    "return_codes": {
      "heat": 0
    },  
    "reason": "timeout",
    "state": "done"
  },
```

**Comment by bd4** [comment]
There is a for this in workflow-scheduling branch, but would is one line fix, I can backport if needed: https://github.com/CODARcode/cheetah/pull/70/files#diff-738bdb94339a71efd2cb7d1c8d941744R511

**Comment by bd4** [comment]
branch merged with fix
