### ISSUE TITLE
Support for input files with key-value parameters

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#82]
We need the ability to modify input ascii files that list application parameters in `key=value` format. Requirement in xgc.

**Comment by bd4** [comment]
Is it an ini format, or even simpler? Can you paste in an example?

**Comment by kshitij-v-mehta** [comment]
Now that you ask, I found they are in Fortran NAMELIST format https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vnc6/index.html

And this is Fortran specific. So I guess boolean values must be represented as `.true.` and `.false.` instead of just `True` and `False`.

Example:
```
&diag_param ! diagnosis
diag_1d_period=1
diag_tavg_on=.true.
diag_tracer_period=10000
diag_3d_on=.true.

/
&neu_param            ! neutral collision
neu_col_mode=0

/
&lim_param            ! limiter 

/
&smooth_param
smooth_mode_in=0
smooth_H_mode_in=2
```

**Comment by bd4** [comment]
I'm inclined to use this module: https://pypi.python.org/pypi/f90nml . We could make it an optional dependency, mask the import so it's only needed if you use that param type.

**Comment by bd4** [comment]
How about something like this:
```
ParamConfig(target='xgc',
                      name='diag_tavg_on',
                      config_file='config.nml',
                      match_string='DIAG_TAVG_ON_VALUE',
                      values=['.true.', '.false.'])
```
Then in the source template, have to use `diag_tavg_on=DIAG_TAVG_ON_VALUE`. Would be nice to have cheetah automatically add the config file to inputs, but adios xml doesn't do that yet (maybe separate feature).

The advantage of this over native nml support is that it is very flexible, and can handle any config file as long as you embed a unique string in it to replace.
