### ISSUE TITLE
Experiments producing no output

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#83]
All experiments following an experiment that timed out produce no output. No stdout or stderr files are written; the experiments do no seem to run.

@bd4 and @kshitij-v-mehta working on the issue.

**Comment by kshitij-v-mehta** [comment]
On Titan, `aprun` is a wrapper that launches child processes. When Cheetah issues a kill command when a run times out, the wrapper process is killed, but the child processes keep running. As a result, no more aprun commands can be launched, and all following experiments get queued.

**Comment by bd4** [comment]
Using Popen start_new_session together with killpg fixes this, but does not work at all on theta. I tried using Popen.terminate instead of kill, hoping that the aprun wrapper would propagate the signal down in the correct way, but it is not addressing the problem.

**Comment by kshitij-v-mehta** [comment]
Pinging ALCF would be a good idea. I wonder how cobalt terminates a job when it times out.

**Comment by bd4** [comment]
Using preexec_fn os.setpgrp instead of start_new_session (which is just os.setsid) fixes the issue on theta, and still allows pgroup signals and fixes issue.
